name = "a0b_timer"
description = "A0B Timer"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "timer"]

project-files = ["gnat/a0b_timer.gpr"]

[configuration]
disabled = true

[[depends-on]]
a0b_base = "*"
a0b_callbacks = "*"
a0b_time = "*"
a0b_timer_platform = "0.1.0"

[origin]
commit = "be29c359370bb7d6c1723c783c123a9c2a9b0095"
url = "git+https://github.com/godunko/a0b-timer.git"

