name = "a0b_stm32h723"
description = "A0B: STM32H723 support"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"

project-files=["gnat/a0b_stm32h723.gpr"]

tags = ["a0b", "embedded", "svd", "stm32", "stm32h7", "stm32h723"]

[configuration]
disabled = true

[[depends-on]]
a0b_base = "*"
a0b_armv7m = "*"
gnat_arm_elf = "*"

[origin]
commit = "26dc0f57e6a937520982b1b6020275a112df9227"
url = "git+https://github.com/godunko/a0b-stm32h723.git"

