name = "a0b_time"
description = "A0B Monotonic Time"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded"]

project-files = ["gnat/a0b_time.gpr"]

[configuration]
disabled = true

[[depends-on]]
a0b_base = "*"
a0b_time_platform = "0.1.0"

[origin]
commit = "a70b9d8ff0ef0b17516f2bdc5c3e23d32bfabe4b"
url = "git+https://github.com/godunko/a0b-time.git"

