name = "a0b_armv7m_systick_clock_timer"
description = "A0B Monotonic Clock and Timer by ARMv7M SysTick"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "time", "timer"]

project-files = ["gnat/a0b_time_platform.gpr", "gnat/a0b_timer_platform.gpr"]

provides = ["a0b_time_platform=0.1.0", "a0b_timer_platform=0.1.0"]

[configuration]
disabled = true

[[depends-on]]
a0b_base = "*"
a0b_armv7m = "*"

[origin]
commit = "acb4e1130556d6d52cf5b50d4365a4efa46eb696"
url = "git+https://github.com/godunko/a0b-armv7m-systick_clock_timer.git"

