name = "a0b_tasking"
description = "A0B Tasking"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
tags = ["embedded", "tasking"]

project-files = ["gnat/a0b_tasking_armv7m.gpr"]

[configuration]
disabled = true

[[depends-on]]
a0b_armv7m = "*"

[origin]
commit = "3f95cc44d20581261794de0c788a4b9f43c9888d"
url = "git+https://github.com/godunko/a0b-tasking.git"

