name = "a0b_i2c"
description = "A0B I2C API"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded"]

project-files = ["gnat/a0b_i2c.gpr"]

[configuration]
disabled = true

[[depends-on]]
a0b_base = "*"
a0b_callbacks = "*"

[origin]
commit = "5c8ebf639c5c9640d7c94e37337ee51670f0bdb6"
url = "git+https://github.com/godunko/a0b-i2c.git"

