name = "a0b_base"
description = "A0B: Base components"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["types", "builtins"]

project-files=["gnat/a0b_base.gpr"]

[configuration]
disabled = true

[origin]
commit = "7db8cebe476b47c7a77c660a9f7048c9d70d3e9d"
url = "git+https://github.com/godunko/a0b-base.git"

