name = "a0b_stm32f401_i2c"
description = "A0B: STM32F401 I2C"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "i2c", "stm32", "stm32f4", "stm32f401"]

project-files = ["gnat/a0b_stm32f401_i2c.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_base = "*"
a0b_i2c = "*"
a0b_stm32f401_dma = "*"
a0b_stm32f401_gpio = "*"

[origin]
commit = "dd9f053e7f0a6afe1213705745e6f0f69eaee201"
url = "git+https://github.com/godunko/a0b-stm32f401-i2c.git"

