name = "light_arduino_due"
description = "Arduino Due Board Support Package for `light` GNAT Runtime"
version = "0.2.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"

project-files=["gnat/arduino_due_startup.gpr"]

tags = ["a0b", "embedded", "bsp", "light", "sam3x8e", "arduino", "due"]

[configuration]
disabled = true

[configuration.values]
a0b_armv7m.fpu_extension = "none"

[[depends-on]]
gnat_arm_elf = "*"
a0b_base = "*"
a0b_armv7m = "*"
a0b_atsam3x8e = "*"

[origin]
commit = "08433d79de9e17e6b52da99e442a878f7f289e88"
url = "git+https://github.com/godunko/light-startup.git"

