name = "a0b_stm32f401_dma"
description = "A0B: STM32F401 DMA"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "stm32", "stm32f4", "stm32f401"]

project-files = ["gnat/a0b_stm32f401_dma.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_base = "*"
a0b_callbacks = "*"
a0b_stm32f401 = "*"

[origin]
commit = "333f16309ea342e91df5c24c9623c25852a2a63a"
url = "git+https://github.com/godunko/a0b-stm32f401-dma.git"

