name = "a0b_pca9685"
description = "A0B: PCA9685 driver"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded"]

project-files = ["gnat/a0b_pca9685.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_base = "*"
a0b_i2c = "*"

[origin]
commit = "e9a106f2d6eed89bcb8c5efa6bc64deb4bde5bed"
url = "git+https://github.com/godunko/a0b-pca9685.git"

